### ISSUE TITLE
Change GitHub username

### ISSUE THREAD

**Issue by aleksandryuryev** [synthes/public_test#1]
Hello. I see your github account (github.com/synthes) is not in use, could you please release the username (synthes) if possible? We would like to place a project of the same name at this username and would be very grateful to you. It would be sufficient to change the username to something else. Thanks.

**Comment by ise-synthesis** [comment]
We can't release this username because some private repositories are in use.

**Comment by aleksandryuryev** [comment]
@ise-synthesis ok. Could you please delete this issue. Thanks.
